// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPIlwWhnPwVqHnTeQ9TLDUe4yGfy1XZn0',
    appId: '1:153607824453:web:a65258c8523f070a51ef2c',
    messagingSenderId: '153607824453',
    projectId: 'triptailor-f15a8',
    authDomain: 'triptailor-f15a8.firebaseapp.com',
    storageBucket: 'triptailor-f15a8.appspot.com',
    measurementId: 'G-ZKS0F8DB0R',
    databaseURL: 'https://triptailor-f15a8-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhN_Uykjkf_MK5P1OE2BcQLs83BBbTKe4',
    appId: '1:153607824453:android:d89faac8dc55607c51ef2c',
    messagingSenderId: '153607824453',
    projectId: 'triptailor-f15a8',
    storageBucket: 'triptailor-f15a8.appspot.com',
    databaseURL: 'https://triptailor-f15a8-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1eLddaRgwzAc5NKWUT_ULKtqYmGLuloY',
    appId: '1:153607824453:ios:0ab68506e4d8622d51ef2c',
    messagingSenderId: '153607824453',
    projectId: 'triptailor-f15a8',
    storageBucket: 'triptailor-f15a8.appspot.com',
    iosBundleId: 'com.example.project',
    databaseURL: 'https://triptailor-f15a8-default-rtdb.firebaseio.com/',

  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1eLddaRgwzAc5NKWUT_ULKtqYmGLuloY',
    appId: '1:153607824453:ios:00b5a153306ec2b351ef2c',
    messagingSenderId: '153607824453',
    projectId: 'triptailor-f15a8',
    storageBucket: 'triptailor-f15a8.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
    databaseURL: 'https://triptailor-f15a8-default-rtdb.firebaseio.com/',
  );
}
